export const locationArray = [
  { label: "* Select Location", value: 0 },
  { label: "Mumbai, Maharashtra", value: "Mumbai, Maharashtra" },
  { label: "Delhi, Delhi", value: "Delhi, Delhi" },
  { label: "Bengaluru, Karnataka", value: "Bengaluru, Karnataka" },
  { label: "Hyderabad, Telangana", value: "Hyderabad, Telangana" },
  { label: "Ahmedabad, Gujarat", value: "Ahmedabad, Gujarat" },
  { label: "Chennai, Tamilnadu", value: "Chennai, Tamilnadu" },
  { label: "Kolkata, West Bengal", value: "Kolkata, West Bengal" },
  { label: "Surat, Gujarat", value: "Surat, Gujarat" },
  { label: "Pune, Maharashtra", value: "Pune, Maharashtra" },
  { label: "Jaipur, Rajasthan", value: "Jaipur, Rajasthan" },
  { label: "Lucknow, Uttar Pradesh", value: "Lucknow, Uttar Pradesh" },
  { label: "Kanpur, Uttar Pradesh", value: "Kanpur, Uttar Pradesh" },
  { label: "Nagpur, Maharashtra", value: "Nagpur, Maharashtra" },
  {
    label: "Visakhapatnam, Andhra Pradesh",
    value: "Visakhapatnam, Andhra Pradesh"
  },
  { label: "Indore, Madhya Pradesh", value: "Indore, Madhya Pradesh" },
  { label: "Thane, Maharashtra", value: "Thane, Maharashtra" },
  { label: "Bhopal, Madhya Pradesh", value: "Bhopal, Madhya Pradesh" },
  { label: "Patna, Bihar", value: "Patna, Bihar" },
  { label: "Vadodara, Gujarat", value: "Vadodara, Gujarat" },
  { label: "Ghaziabad, Uttar Pradesh", value: "Ghaziabad, Uttar Pradesh" },
  { label: "Ludhiana, Punjab", value: "Ludhiana, Punjab" },
  { label: "Coimbatore, Tamilnadu", value: "Coimbatore, Tamilnadu" },
  { label: "Agra, Uttar Pradesh", value: "Agra, Uttar Pradesh" },
  { label: "Madurai, Tamilnadu", value: "Madurai, Tamilnadu" },
  { label: "Nashik, Maharashtra", value: "Nashik, Maharashtra" },
  { label: "Faridabad, Haryana", value: "Faridabad, Haryana" },
  { label: "Meerut, Uttar Pradesh", value: "Meerut, Uttar Pradesh" },
  { label: "Rajkot, Gujarat", value: "Rajkot, Gujarat" },
  { label: "Kalyan, Maharashtra", value: "Kalyan, Maharashtra" },
  { label: "Vasai, Maharashtra", value: "Vasai, Maharashtra" },
  { label: "Varanasi, Uttar Pradesh", value: "Varanasi, Uttar Pradesh" },
  {
    label: "Srinagar, Jammu &amp; Kashmir",
    value: "Srinagar, Jammu &amp; Kashmir"
  },
  { label: "Aurangabad, Maharashtra", value: "Aurangabad, Maharashtra" },
  { label: "Dhanbad, Jharkhand", value: "Dhanbad, Jharkhand" },
  { label: "Amritsar, Punjab", value: "Amritsar, Punjab" },
  { label: "Navi Mumbai, Maharashtra", value: "Navi Mumbai, Maharashtra" },
  { label: "Prayagraj, Uttar Pradesh", value: "Prayagraj, Uttar Pradesh" },
  { label: "Ranchi, Jharkhand", value: "Ranchi, Jharkhand" },
  { label: "Howrah, West Bengal", value: "Howrah, West Bengal" },
  { label: "Jabalpur, Madhya Pradesh", value: "Jabalpur, Madhya Pradesh" },
  { label: "Gwalior, Madhya Pradesh", value: "Gwalior, Madhya Pradesh" },
  {
    label: "Vijaywada, Andhra Pradesh",
    value: "Vijaywada, Andhra Pradesh"
  },
  { label: "Jodhpur, Rajasthan", value: "Jodhpur, Rajasthan" },
  { label: "Raipur, Chhattisgarh", value: "Raipur, Chhattisgarh" },
  { label: "Kota, Rajasthan", value: "Kota, Rajasthan" },
  { label: "Guwahati, Assam", value: "Guwahati, Assam" },
  { label: "Chandigarh, Chandigarh", value: "Chandigarh, Chandigarh" },
  { label: "Solapur, Maharashtra", value: "Solapur, Maharashtra" },
  {
    label: "Tiruchirappalli, Tamilnadu",
    value: "Tiruchirappalli, Tamilnadu"
  },
  { label: "Bareilly, Uttar Pradesh", value: "Bareilly, Uttar Pradesh" },
  { label: "Mysore, Karnataka", value: "Mysore, Karnataka" },
  { label: "Tiruppur, Tamilnadu", value: "Tiruppur, Tamilnadu" },
  { label: "Gurgaon, Haryana", value: "Gurgaon, Haryana" },
  { label: "Aligarh, Uttar Pradesh", value: "Aligarh, Uttar Pradesh" },
  { label: "Jalandhar, Punjab", value: "Jalandhar, Punjab" },
  { label: "Bhubaneswar, Odisha", value: "Bhubaneswar, Odisha" },
  { label: "Salem, Tamilnadu", value: "Salem, Tamilnadu" },
  { label: "Warangal, Telangana", value: "Warangal, Telangana" },
  {
    label: "Thiruvananthapuram, Kerala",
    value: "Thiruvananthapuram, Kerala"
  },
  { label: "Guntur, Andhra Pradesh", value: "Guntur, Andhra Pradesh" },
  { label: "Bhiwandi, Maharashtra", value: "Bhiwandi, Maharashtra" },
  {
    label: "Saharanpur, Uttar Pradesh",
    value: "Saharanpur, Uttar Pradesh"
  },
  { label: "Gorakhpur, Uttar Pradesh", value: "Gorakhpur, Uttar Pradesh" },
  { label: "Bikaner, Rajasthan", value: "Bikaner, Rajasthan" },
  { label: "Amravati, Maharashtra", value: "Amravati, Maharashtra" },
  { label: "Noida, Uttar Pradesh", value: "Noida, Uttar Pradesh" },
  { label: "Jamshedpur, Jharkhand", value: "Jamshedpur, Jharkhand" },
  { label: "Bhilai, Chhattisgarh", value: "Bhilai, Chhattisgarh" },
  { label: "Cuttak, Odisha", value: "Cuttak, Odisha" },
  { label: "Firozabad, Uttar Pradesh", value: "Firozabad, Uttar Pradesh" },
  { label: "Kochi, Kerala", value: "Kochi, Kerala" },
  { label: "Nellore, Andhra Pradesh", value: "Nellore, Andhra Pradesh" },
  { label: "Bhavnagar, Gujarat", value: "Bhavnagar, Gujarat" },
  { label: "Dehradun, Uttarakhand", value: "Dehradun, Uttarakhand" },
  { label: "Durgapur, West Bengal", value: "Durgapur, West Bengal" },
  { label: "Asansol, West Bengal", value: "Asansol, West Bengal" },
  { label: "Rourkela, Odisha", value: "Rourkela, Odisha" },
  { label: "Nanded, Maharashtra", value: "Nanded, Maharashtra" },
  { label: "Kolhapur, Maharashtra", value: "Kolhapur, Maharashtra" },
  { label: "Ajmer, Rajasthan", value: "Ajmer, Rajasthan" },
  { label: "Akola, Maharashtra", value: "Akola, Maharashtra" },
  { label: "Gulbarga, Karnataka", value: "Gulbarga, Karnataka" },
  { label: "Jamnagar, Gujarat", value: "Jamnagar, Gujarat" }
];

export default locationArray;
